# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    secure: ESN9LMfyOZo8AFi97XIkRKVYMC7JVM0MtDEx0uBzcQ4tXA3mxAxWelcXiCHtBLVLmSzLmVCaB2E7PeU90xCAtcriGb86fwL3RSrHp1YCANHuGFTpp1wU3f73kFKMWo/XkZ0l+g5B97vSV/JeC5WVQzd6Z+DNXfl7HARjBQmDgsnrswJvpr9L0L+zHA9vaxFuTMnPDyNEBegbWHqeLQl83Q6Re6EArF6qKiYJpqQm2t1PN7T0Xul6utB03uNbYfuFHkIJ5j7pGseui4DSw2JHy89gGI0eVdL1txcNU/74Ql0kuQ80xjGQrL51Oxctslk1n0FEsVbUHZvSCjT6CPx3SbItbGbc3PHr0UNlqjbxcGQX74jWDEIpdV+S0TAyBsieuKQ3eXhd9S0O5VoJSEWQ8iBy+NW7vQUdck69aPWTUFynnFUWolRk5s9bSeOGVFcWlHYd+1bJ4lkgUh5o048YaZ9iq9Bptvgw95Q1LYHnYMvXiRsBreulwfl19mPDWeSz4/gzStXpj9WZ9cPquAReyC9EGkVdi+sPLKNEg+RmBefgHX7RQbxk+qn5se8wSwElf25mLAUGKmejuX8OiD96IFspdtOweWJkpJoLo1bKp18VQrC9+gmFH5JoKc4WHqOiE3NyiN/DdVk64boC7+8SbELYexhEBlX88+QrNN7RvE8=
    # SAUCE_TOKENS
    # - secure: m9BMEAR49UjfnSITCWkW0b6RsJ6TwP+EexDNJaEeSZsODOzYK6zR1JKQBVgF5JhSnuZjkXBmncdax1LirADhEw504Bl3a/zMlxQm+GpwTcMHikZQCXTRUtZOKCq31AM8pufAK/9fGFPAdUtgt4takc0RaBrS/tFbDKGOsUy+3H/ymZSI2BGBlrKZD+gaZzlX9dnEY2EwwJKHdFvnjf14eVab1DUXav0I9+C3873YgCfLtTf+/Rzb9SeSuCK6jZq3sHffDIfYWtYo5cgNcNBiEmDGGeLDZ/nHDDj2gmcOsO4yjhEvluFg8cOzQMb+5jhxBYL11nBiEU+zvfaVHssZrDIlPYearhE87w3lN3oXoSqpHqzsFu3WssRsl/j0OvDVmF8eHKSOdPz2ZOhlmiV2ZUrszP17+ocS5c22gTAP/mHUNlCsSOFaZNioV2EQ2ljJkM2q+aoEIbTN1Y/99StsJ1gcVpVReZl5PGCsq+R8J6eXrbTwvC86hAM4/uEStIlKJzIYpvQasgNDa4VLEw9DXECWFRZ1xZfaKf4dnGlLrxh1EcWmBPOmVEsWWaFRhCC6THTB6Rpchekcmh/L8WH9Rxw52ctsiliDG84KS/PjMlPCqc5mPhtreghvJatBPT+rKwyU54k83oouqWkfMVtJewVmT4jtw89a7sVwgTH6dfk=
    # - secure: T1JCtjz7KiSVjL/HJ6t1MShL7J43E2bEp6Mq9ki/0K9ZUUBVfSwyPdDu5sxl0oaW27UmYajq/bp3v+C3gdjkFkO35Te4iKyyC8lVL86IvXvIzDlAMP3ILY6VaaaBKVyGx8iWSTWE+oL3wx2Z7Jed1kw96HeJUrWQhC5KWiV1Ar0imq0jreoBd7+3SgIcKCq/UJmSEHea2HP2DTlPexr/CE1Dp9nYzgJa2goHLidlUCgo6WE9b72EbjqW77ww0RNUAbcdS4+DuCEoSo/6kTO5akQD5pJGNFjtQUfNzrM9ZaJLJzPmP6sr9pbL4FOeIpreVvAON4mfuExlYfVj78vssO8TfXAYXvBwKXRz9h0epjnTTup+39g5dig+3Spwvnvy9XHoQ1ySucEBHLLp/64vlf9itXEqiPcNRPqXysLRbZh1E3g3aXOgXOrU437kF/92LuT4pSfWJa6z+j+HsjHQhlS7pFM3l8xYOwl5v/Dc72GowZLO8bLbIvkg7UooZm8TOCpbZlFTMJWgMKkOae+19E6sKsqbe2SBVx/09raKa2DYhVNct12BfrNG6Nal10He4U2pvvmlNykWdV4P0kgVe7WUNNtNV1hyrDTsdQPxPBzw5kWMR4S0PJ+73IwzCry8w7iQ9yUh1wyeflFTwjUwlRt1AjOYu1f7b3Q62bzYEb4=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: XsuWBuptDkzpFGmcgst/QEFJQe1qmqlqWC1n81H7+l1MKid6Pt+7hJ8qJFt8bJ6gW/DgPkyFgvzOMnM4foZqiLvWJDq3GwecXGufLbJVhDoCKS/94bOgqWdKPM3mPEz9L+sACySGABgih1ZEMGcLUZekDqBpYCpyFvLMEsKaIQWLGxWUt4n45WmYDsFNQ+/i8loLvD1/WJbojjtaYsXPbNoO1aqsq3we0ObhI+Oh5VEf+68iBCqoRSwis16mImhQM9cVvNnwHo4/bKYAFp/hWkyLfMY+UB8yz86ycANSHU1z/j+iD3Z2wzAe4Ln/7uiESxjQIUcUKnS/GThJJWRe3A2hjUA8M9Rk+uFkMxdzTJRZq9NwgiuZDPDhjZho9T0eYyc4H8xt46Pixdo0jxRwHRHChMYH2pk7b4U5bSUQp2NqUr3x8KHlOtO5Hz/P3X2NNkw0Zl8j2BPlvGf6OSB5Lp8nXQXkOwaqd6dyQB9BPBRDLtMY0ky2zKKyLxvZjNXfxBs17shaooBkC9VfAryfZ4OnKNN0uYKTj/i7q5hnkpWf+AOEiLjNe7JUxTo3DROUVxdDdvZFsLl6t+1qrLBoZL5mxOzFI7+y87MMGy8z32NxP+W9wN4x73DvGz/ZwVnQWmWPpV/TJ+Ub9BO/aqqgB1kIPdUyXl7cuhOKSoqLtsY=

# Cloud testing
# after_deploy:
#   - npm install
#   - npm install zuul --global
#   - npm run test-cloud